-- ═══════════════════════════════════════════════════════════════
--  OG Jobs · Seed dữ liệu nền (countries / companies / skills / fx_rates)
--
--  File này TƯƠNG ĐƯƠNG apps/api/src/scripts/seed.ts, viết bằng SQL thuần
--  để dùng khi trên máy KHÔNG có Node/pnpm: dán thẳng vào SQL Editor của
--  Neon / Supabase, hoặc chạy `psql -f seed.sql`.
--
--  ⚠️ Phải chạy SAU khi migration đã tạo bảng (API khởi động lần đầu sẽ
--     tự chạy `prisma migrate deploy`).
--  ✅ Chạy lại nhiều lần vẫn an toàn — mọi câu đều có ON CONFLICT.
-- ═══════════════════════════════════════════════════════════════

BEGIN;

-- ─────────── countries (49) ───────────
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('US', 'USA', 'United States', 'North America', 'USD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('CA', 'CAN', 'Canada', 'North America', 'CAD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('MX', 'MEX', 'Mexico', 'Latin America', 'MXN') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('BR', 'BRA', 'Brazil', 'Latin America', 'BRL') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('AR', 'ARG', 'Argentina', 'Latin America', 'ARS') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('CO', 'COL', 'Colombia', 'Latin America', 'COP') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('GY', 'GUY', 'Guyana', 'Latin America', 'GYD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('TT', 'TTO', 'Trinidad and Tobago', 'Latin America', 'TTD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('VE', 'VEN', 'Venezuela', 'Latin America', 'VES') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('GB', 'GBR', 'United Kingdom', 'Europe', 'GBP') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('NO', 'NOR', 'Norway', 'Europe', 'NOK') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('NL', 'NLD', 'Netherlands', 'Europe', 'EUR') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('DK', 'DNK', 'Denmark', 'Europe', 'DKK') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('DE', 'DEU', 'Germany', 'Europe', 'EUR') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('FR', 'FRA', 'France', 'Europe', 'EUR') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('IT', 'ITA', 'Italy', 'Europe', 'EUR') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('RO', 'ROU', 'Romania', 'Europe', 'RON') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('AZ', 'AZE', 'Azerbaijan', 'Caspian', 'AZN') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('KZ', 'KAZ', 'Kazakhstan', 'Caspian', 'KZT') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('RU', 'RUS', 'Russia', 'Caspian', 'RUB') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('AE', 'ARE', 'United Arab Emirates', 'Middle East', 'AED') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('SA', 'SAU', 'Saudi Arabia', 'Middle East', 'SAR') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('QA', 'QAT', 'Qatar', 'Middle East', 'QAR') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('KW', 'KWT', 'Kuwait', 'Middle East', 'KWD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('OM', 'OMN', 'Oman', 'Middle East', 'OMR') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('BH', 'BHR', 'Bahrain', 'Middle East', 'BHD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('IQ', 'IRQ', 'Iraq', 'Middle East', 'IQD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('NG', 'NGA', 'Nigeria', 'Africa', 'NGN') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('AO', 'AGO', 'Angola', 'Africa', 'AOA') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('EG', 'EGY', 'Egypt', 'Africa', 'EGP') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('DZ', 'DZA', 'Algeria', 'Africa', 'DZD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('LY', 'LBY', 'Libya', 'Africa', 'LYD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('GH', 'GHA', 'Ghana', 'Africa', 'GHS') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('CG', 'COG', 'Congo', 'Africa', 'XAF') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('GQ', 'GNQ', 'Equatorial Guinea', 'Africa', 'XAF') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('MZ', 'MOZ', 'Mozambique', 'Africa', 'MZN') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('SN', 'SEN', 'Senegal', 'Africa', 'XOF') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('NA', 'NAM', 'Namibia', 'Africa', 'NAD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('MY', 'MYS', 'Malaysia', 'Asia Pacific', 'MYR') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('ID', 'IDN', 'Indonesia', 'Asia Pacific', 'IDR') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('SG', 'SGP', 'Singapore', 'Asia Pacific', 'SGD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('VN', 'VNM', 'Vietnam', 'Asia Pacific', 'VND') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('TH', 'THA', 'Thailand', 'Asia Pacific', 'THB') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('BN', 'BRN', 'Brunei', 'Asia Pacific', 'BND') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('AU', 'AUS', 'Australia', 'Asia Pacific', 'AUD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('IN', 'IND', 'India', 'Asia Pacific', 'INR') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('CN', 'CHN', 'China', 'Asia Pacific', 'CNY') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('PG', 'PNG', 'Papua New Guinea', 'Asia Pacific', 'PGK') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;
INSERT INTO countries (code, iso3, name, region, currency) VALUES ('TL', 'TLS', 'Timor-Leste', 'Asia Pacific', 'USD') ON CONFLICT (code) DO UPDATE SET iso3=EXCLUDED.iso3, name=EXCLUDED.name, region=EXCLUDED.region, currency=EXCLUDED.currency;

-- ─────────── companies (38) ───────────
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('slb', 'SLB', 'SERVICE'::"CompanyType", 'https://www.slb.com', 'https://careers.slb.com', (SELECT id FROM countries WHERE code = 'US'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('baker-hughes', 'Baker Hughes', 'SERVICE'::"CompanyType", 'https://www.bakerhughes.com', 'https://careers.bakerhughes.com', (SELECT id FROM countries WHERE code = 'US'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('halliburton', 'Halliburton', 'SERVICE'::"CompanyType", 'https://www.halliburton.com', 'https://jobs.halliburton.com', (SELECT id FROM countries WHERE code = 'US'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('weatherford', 'Weatherford', 'SERVICE'::"CompanyType", 'https://www.weatherford.com', NULL, (SELECT id FROM countries WHERE code = 'US'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('exxonmobil', 'ExxonMobil', 'IOC'::"CompanyType", 'https://corporate.exxonmobil.com', 'https://jobs.exxonmobil.com', (SELECT id FROM countries WHERE code = 'US'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('chevron', 'Chevron', 'IOC'::"CompanyType", 'https://www.chevron.com', 'https://careers.chevron.com', (SELECT id FROM countries WHERE code = 'US'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('conocophillips', 'ConocoPhillips', 'IOC'::"CompanyType", 'https://www.conocophillips.com', NULL, (SELECT id FROM countries WHERE code = 'US'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('bp', 'bp', 'IOC'::"CompanyType", 'https://www.bp.com', 'https://www.bp.com/en/global/corporate/careers.html', (SELECT id FROM countries WHERE code = 'GB'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('shell', 'Shell', 'IOC'::"CompanyType", 'https://www.shell.com', 'https://www.shell.com/careers.html', (SELECT id FROM countries WHERE code = 'GB'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('totalenergies', 'TotalEnergies', 'IOC'::"CompanyType", 'https://totalenergies.com', 'https://careers.totalenergies.com', (SELECT id FROM countries WHERE code = 'FR'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('eni', 'Eni', 'IOC'::"CompanyType", 'https://www.eni.com', NULL, (SELECT id FROM countries WHERE code = 'IT'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('equinor', 'Equinor', 'IOC'::"CompanyType", 'https://www.equinor.com', 'https://www.equinor.com/careers', (SELECT id FROM countries WHERE code = 'NO'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('aker-bp', 'Aker BP', 'IOC'::"CompanyType", 'https://www.akerbp.com', NULL, (SELECT id FROM countries WHERE code = 'NO'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('woodside-energy', 'Woodside Energy', 'IOC'::"CompanyType", 'https://www.woodside.com', NULL, (SELECT id FROM countries WHERE code = 'AU'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('petronas', 'Petronas', 'NOC'::"CompanyType", 'https://www.petronas.com', 'https://www.petronas.com/careers', (SELECT id FROM countries WHERE code = 'MY'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('adnoc', 'ADNOC', 'NOC'::"CompanyType", 'https://www.adnoc.ae', 'https://careers.adnoc.ae', (SELECT id FROM countries WHERE code = 'AE'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('saudi-aramco', 'Saudi Aramco', 'NOC'::"CompanyType", 'https://www.aramco.com', 'https://www.aramco.com/en/careers', (SELECT id FROM countries WHERE code = 'SA'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('qatarenergy', 'QatarEnergy', 'NOC'::"CompanyType", 'https://www.qatarenergy.qa', NULL, (SELECT id FROM countries WHERE code = 'QA'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('koc-kuwait-oil-company', 'KOC (Kuwait Oil Company)', 'NOC'::"CompanyType", 'https://www.kockw.com', NULL, (SELECT id FROM countries WHERE code = 'KW'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('pdo-petroleum-development-oman', 'PDO (Petroleum Development Oman)', 'NOC'::"CompanyType", 'https://www.pdo.co.om', NULL, (SELECT id FROM countries WHERE code = 'OM'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('petrobras', 'Petrobras', 'NOC'::"CompanyType", 'https://petrobras.com.br', NULL, (SELECT id FROM countries WHERE code = 'BR'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('sonangol', 'Sonangol', 'NOC'::"CompanyType", 'https://www.sonangol.co.ao', NULL, (SELECT id FROM countries WHERE code = 'AO'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('nnpc', 'NNPC', 'NOC'::"CompanyType", 'https://www.nnpcgroup.com', NULL, (SELECT id FROM countries WHERE code = 'NG'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('pttep', 'PTTEP', 'NOC'::"CompanyType", 'https://www.pttep.com', NULL, (SELECT id FROM countries WHERE code = 'TH'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('petrovietnam-pvn', 'PetroVietnam (PVN)', 'NOC'::"CompanyType", 'https://www.pvn.vn', NULL, (SELECT id FROM countries WHERE code = 'VN'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('kazmunaygas', 'KazMunayGas', 'NOC'::"CompanyType", 'https://www.kmg.kz', NULL, (SELECT id FROM countries WHERE code = 'KZ'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('tullow-oil', 'Tullow Oil', 'IOC'::"CompanyType", 'https://www.tullowoil.com', NULL, (SELECT id FROM countries WHERE code = 'GB'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('harbour-energy', 'Harbour Energy', 'IOC'::"CompanyType", 'https://www.harbourenergy.com', NULL, (SELECT id FROM countries WHERE code = 'GB'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('wood', 'Wood', 'EPC'::"CompanyType", 'https://www.woodplc.com', NULL, (SELECT id FROM countries WHERE code = 'GB'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('petrofac', 'Petrofac', 'EPC'::"CompanyType", 'https://www.petrofac.com', NULL, (SELECT id FROM countries WHERE code = 'GB'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('technipfmc', 'TechnipFMC', 'EPC'::"CompanyType", 'https://www.technipfmc.com', NULL, (SELECT id FROM countries WHERE code = 'GB'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('saipem', 'Saipem', 'EPC'::"CompanyType", 'https://www.saipem.com', NULL, (SELECT id FROM countries WHERE code = 'IT'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('subsea7', 'Subsea7', 'EPC'::"CompanyType", 'https://www.subsea7.com', NULL, (SELECT id FROM countries WHERE code = 'GB'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('worley', 'Worley', 'EPC'::"CompanyType", 'https://www.worley.com', NULL, (SELECT id FROM countries WHERE code = 'AU'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('rps-gaffney-cline', 'RPS / Gaffney Cline', 'CONSULTANCY'::"CompanyType", 'https://www.gaffneycline.com', NULL, (SELECT id FROM countries WHERE code = 'GB'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('degolyer-and-macnaughton', 'DeGolyer and MacNaughton', 'CONSULTANCY'::"CompanyType", 'https://www.demac.com', NULL, (SELECT id FROM countries WHERE code = 'US'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('rigzone-board', 'Rigzone (board)', 'JOB_BOARD'::"CompanyType", 'https://www.rigzone.com', NULL, (SELECT id FROM countries WHERE code = 'US'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();
INSERT INTO companies (slug, name, type, website, careers_url, hq_country_id, updated_at) VALUES ('oil-and-gas-job-search-board', 'Oil and Gas Job Search (board)', 'JOB_BOARD'::"CompanyType", 'https://www.oilandgasjobsearch.com', NULL, (SELECT id FROM countries WHERE code = 'GB'), NOW()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, type=EXCLUDED.type, website=EXCLUDED.website, careers_url=EXCLUDED.careers_url, hq_country_id=EXCLUDED.hq_country_id, updated_at=NOW();

-- ─────────── skills (32) ───────────
INSERT INTO skills (slug, name, category) VALUES ('petrel', 'Petrel', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('eclipse', 'Eclipse', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('intersect', 'INTERSECT', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('cmg', 'CMG (GEM/IMEX/STARS)', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('tnavigator', 'tNavigator', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('techlog', 'Techlog', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('ip-senergy', 'Interactive Petrophysics', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('geolog', 'Geolog', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('kingdom', 'Kingdom', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('opendtect', 'OpendTect', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('prosper', 'PROSPER', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('gap', 'GAP', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('mbal', 'MBAL', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('pipesim', 'PIPESIM', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('olga', 'OLGA', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('saphir', 'KAPPA Saphir', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('wellplan', 'WELLPLAN', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('compass', 'Landmark COMPASS', 'SOFTWARE'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('python', 'Python', 'PROGRAMMING'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('matlab', 'MATLAB', 'PROGRAMMING'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('sql', 'SQL', 'PROGRAMMING'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('machine-learning', 'Machine Learning', 'PROGRAMMING'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('history-matching', 'History Matching', 'DOMAIN'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('nodal-analysis', 'Nodal Analysis', 'DOMAIN'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('formation-evaluation', 'Formation Evaluation', 'DOMAIN'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('seismic-interpretation', 'Seismic Interpretation', 'DOMAIN'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('well-testing', 'Well Testing', 'DOMAIN'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('eor', 'EOR / IOR', 'DOMAIN'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('flow-assurance', 'Flow Assurance', 'DOMAIN'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('artificial-lift', 'Artificial Lift', 'DOMAIN'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('reserves-prms', 'Reserves / PRMS', 'DOMAIN'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;
INSERT INTO skills (slug, name, category) VALUES ('hse', 'HSE', 'DOMAIN'::"SkillCategory") ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category;

-- ─────────── fx_rates (47) — tỉ giá dự phòng, cron sẽ ghi đè bằng số thật ───────────
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('USD', 1) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('EUR', 0.92) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('GBP', 0.79) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('NOK', 10.6) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('DKK', 6.9) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('SEK', 10.5) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('CAD', 1.36) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('AUD', 1.52) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('AED', 3.67) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('SAR', 3.75) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('QAR', 3.64) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('KWD', 0.31) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('OMR', 0.385) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('BHD', 0.376) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('MYR', 4.7) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('SGD', 1.35) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('INR', 83.2) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('IDR', 15800) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('BRL', 5.1) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('NGN', 1450) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('EGP', 47) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('KZT', 450) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('RUB', 92) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('CNY', 7.2) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('THB', 36) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('VND', 25000) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('MXN', 17.1) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('ARS', 900) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('COP', 3950) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('GYD', 209) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('TTD', 6.8) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('DZD', 134) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('LYD', 4.85) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('GHS', 14.5) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('XAF', 604) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('XOF', 604) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('NAD', 18.6) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('MZN', 63.8) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('AOA', 850) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('IQD', 1310) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('RON', 4.58) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('PGK', 3.8) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('AZN', 1.7) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('VES', 36) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('ZAR', 18.5) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('BND', 1.35) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();
INSERT INTO fx_rates (code, rate_to_usd) VALUES ('TWD', 32) ON CONFLICT (code) DO UPDATE SET rate_to_usd=EXCLUDED.rate_to_usd, fetched_at=NOW();

COMMIT;

-- ─────────── Kiểm chứng ───────────
SELECT 'countries' AS bang, COUNT(*) AS so_dong FROM countries
UNION ALL SELECT 'companies', COUNT(*) FROM companies
UNION ALL SELECT 'skills',    COUNT(*) FROM skills
UNION ALL SELECT 'fx_rates',  COUNT(*) FROM fx_rates;
